# Generated by Django 4.1.2 on 2022-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
